name: 'lapd_crime_project'
version: '1.0.0'

profile: 'lapd_crime_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lapd_crime_project:
    marts:
      core:
        +schema: mart_core

    # Adding Elementary models to the dbt_project.yml
  elementary:
    +schema: elementary  # This schema will store the Elementary models
    +enabled: true  # This ensures the Elementary models are run by dbt

seeds:
  lapd_crime_project:
    mocodes:
      +column_types:
        mocodes: integer
        description: string
